dubbo:
  application:
    name: controller
  registries:
    registry1:
      address: zookeeper://192.168.31.152:2181
    registry2:
      address: zookeeper://192.168.31.225:2181
  protocol:
    name: dubbo
    port: 20881
server:
  port: 8082
